### PR TITLE
go api code example

### PR DESCRIPTION
**Pull request by omerfruk**
ı thing is correct place :)

### CODE REVIEW

**Comment by dr5hn** [comment]
@omerfruk Thanks so much! This wworks!

**Comment by omerfruk** [comment]
bro why don't merge this pr ?

**Comment by dr5hn** [comment]
@omerfruk Sorry for the delayed response. Can you please write this up for all routes? Currently, you've added only for all-countries.

**Comment by omerfruk** [comment]
Done! You can merge now.

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
